### ISSUE TITLE
[Bug]: Out of memory

### ISSUE THREAD

**Issue by sandangel** [wallpants/github-preview.nvim#171]
### What happened?

After installing the plugin, try opening github-preview with GithubPreviewToggle.
I got the notification saying github-preview: init.

After 10s, the terminal crash saying it's using too much memory.

I guess the plugin load all the files into memory to display on browser.

### What browsers are you seeing the problem on?

Firefox

### :checkhealth

```shell
github-preview: require("github-preview.health").check()

github-preview.nvim ~
- platform: linux
- git-commit: a4c7dd98eb274834bfe15629b540fe13ead83b06
- OK bun: 1.0.7


```

**Comment by wallpants** [comment]
does that happen every time you try opening the plugin? or does it only happen when starting the plugin in a repo with many files? If so, do you know around how many files/levels there are in the repo?

**Comment by wallpants** [comment]
or is there anything different in the repo where this is happening compared to others where this doesn't happen

**Comment by wallpants** [comment]
The plugin doesn't load all the files into memory, but it does traverse the entire repo to get the names of the files. The contents of the files are not accessed until you navigate to that file either via the browser or neovim. I would be surprised if there was a memory problem from getting the names of the files.

**Comment by wallpants** [comment]
Also, did the browser ever open and did anything load?

**Comment by sandangel** [comment]
The browser never open. nothing load. It only shows github-preview: init in notification history. Is there a way to enable more logs?

**Comment by sandangel** [comment]
Actually, I tried on small repo as well but it does not work. Could be because I'm using nix with devenv, direnv? devenv will create a `.devenv` directory with symlinks to all packages within /nix/store? I'm not sure how github-preview traverse the dir tree.

**Comment by wallpants** [comment]
We also run `bun install` every time before the bun app starts, that could also be the step taking up all the memory.

try adding a `log_level` to your plugin config:

```lua
require("github-preview").setup({
	-- ...other settings
	log_level = "verbose"
})
```

this should print out stuff to your neovim `:messages` and you should now also be able to run the following command in a new terminal to get detailed logs live from the bun app:

```sh
bunx bunvim logs github-preview
```

**Comment by sandangel** [comment]
Hi, I managed to make the browser open. After adding log_level, it started to work. I notice that the kitty terminal/neovim was freezed for like 10s. When I expect it crashes, the browser open! YAY!!!!. And the next time I open with GithubPreviewToggle command, it opens browser without issue.

Things I changed: I upgraded bun from 1.0.7 to 1.0.11, which might fix some issues with memory loading.

The performance is still not great. There are some lags like 5~10 seconds when you open a new folder in the sidebar. Also it takes around ~10sec to open a file to view. All of these happens only the first time you open the file or closing github preview and reopen it.

I guess the file loading is not very fast. You might want to take a look at how nvim-tree or neo-tree implement it. 

Some suggestions: 
- We can preload file system in the background so it will be ready when user open it.
- Use background jobs / async jobs so it won't freeze the UI.

**Comment by wallpants** [comment]
There must be something else.

I'm testing the plugin on a base macbbook bro 2.6 GHz 6-Core Intel Core i7, 16 GB ram and everything is pretty much instant.

When opening a folder, we use [globby](https://github.com/sindresorhus/globby) to get a list of files/dirs. Globby is based on [fast-glob](https://github.com/mrmlnc/fast-glob) which claims to be the fastest in nodejs.

When reading the contents of a file we're doing it the way bun says is ["heavily optimized and represent the recommended way to perform file-system tasks using Bun."](https://bun.sh/docs/api/file-io)

what are the specs of your machine?

**Comment by sandangel** [comment]
My spec:
- Linux, Fedora.
- 32GB ram, 6-core

**Comment by sandangel** [comment]
Since I get it working, I think we can close the issue now. Will reopen if I experience this issue again.
