### ISSUE TITLE
[Bug]: App was not killed after NeoVim was terminated.

### ISSUE THREAD

**Issue by Thiago4532** [wallpants/github-preview.nvim#249]
### What happened?

![image](https://github.com/wallpants/github-preview.nvim/assets/19158283/8eda8e6e-bb1e-4fd9-8d20-469c123357e5)
After closing the terminal, the app wasn't closed. I was able to reproduce this after accidentally opening a Markdown file in my home directory and the app froze for some seconds (I assume it was traversing the directory, but traversing home is expensive). While it was scanning I closed the terminal and the app continued to run.

### How were you expecting the plugin to behave?

After the app unfreezes, or even before it does, it should detect that NeoVim was closed and terminate itself.

Also it would be nice if I was able to open Markdown files at home directory without the whole app freezing, since it's running in single-file mode I can't see a reason to take so long to open the file when in the home directory. Is this a bug too?

### :checkhealth

```shell
github-preview: require("github-preview.health").check()

github-preview.nvim ~
- platform: arch
- ERROR failed to read git-commit hash
- OK bun: 1.0.14
```

**Comment by wallpants** [comment]
The plugin has been updated to not try and look for a repository root if single-file mode has been explicitly enabled in your plugin config. This should speed up startup in some cases.

I have not been able to reproduce the app not being killed. I would like to believe that Neovim freezing and being unable to notify the app to shut down is not going to be a common issue. Also if you were to try starting the app again in the same neovim instance or any other neovim instances, the previously ran plugin will be shut down and a new instance will be started. The new instance should die down when your neovim instance exits.

I'm going to mark this issue as resolved. I hope the quicker startup will prevent your Neovim from freezing and having a zombie app running in the background. If you encounter this again, please feel free to open an issue and I'll look into it again.
