### ISSUE TITLE
[Bug]: Empty preview using Bun >= 1.1.25

### ISSUE THREAD

**Issue by michaelo-spindance** [wallpants/github-preview.nvim#398]
### What happened? How were you expecting the plugin to behave?

I installed the latest release of Bun (1.1.26) and when I toggle preview I get the following:

![image](https://github.com/user-attachments/assets/56301bc3-3641-479b-8dbf-0f224df61aca)

After rolling back to version 1.1.24 everything looks to be rendering correctly.

![image](https://github.com/user-attachments/assets/3d62249f-1092-4b60-8d02-0ab4ccde74dd)

Enabling logs provides the following error:

```
01:07:51 PM msg_show job# 4:
01:07:51 PM msg_show $ bun run app/index.ts
01:07:52 PM msg_show ----------------
01:07:52 PM msg_show job# 4:
01:07:52 PM msg_show 19 |     },
01:07:52 PM msg_show 20 | };
01:07:52 PM msg_show 21 | 
01:07:52 PM msg_show 22 | export function httpHandler(app: GithubPreview) {
01:07:52 PM msg_show 23 |     return async (req: Request, server: Server) => {
01:07:52 PM msg_show 24 |         const upgradedToWs = server.upgrade(req, {
01:07:52 PM msg_show                                          ^
01:07:52 PM msg_show TypeError: upgrade options.headers must be a Headers or an object
01:07:52 PM msg_show  code: "ERR_INVALID_ARG_TYPE"
01:07:52 PM msg_show       at ~/.local/share/nvim/lazy/github-preview.nvim/app/server/http.ts:24:37
01:07:52 PM msg_show       at ~/.local/share/nvim/lazy/github-preview.nvim/app/server/http.ts:23:19
01:07:52 PM msg_show GET - / failed
```

### :checkhealth

```shell
==============================================================================
github-preview: require("github-preview.health").check()

github-preview.nvim ~
- platform: pop
- git-commit: b1f286a
- OK bun: 1.1.25
```

**Comment by wallpants** [comment]
Thank you for taking the time to open this issue.

A PR with a fix https://github.com/wallpants/github-preview.nvim/pull/400 has been merged.

Could you please verify that the update fixes the issue on your end?

**Comment by michaelo-spindance** [comment]
@wallpants I confirmed that the update fixed my issue. Thanks!
